### ISSUE TITLE
configurable timout

### ISSUE THREAD

**Issue by PSLLSP** [clvLabs/BusPirate#3]
I found this Python script interesting to upload and run BASIC scripts to BusPirate device. It works great for scripts that are fast. An example:
```
$ cat test6.bp 
s
new
10 AUX 1
20 FOR I=1 TO 5
30 LET A=ADC
40 PRINT I;": ";A
50 DELAY 20
60 NEXT I
70 AUX 0
80 PRINT "WORK DONE"
list
run
exit
```
```
$ python3 buspirate.py -c /dev/ttyUSB2 test6.bp

***[ Bus Pirate scripting tool ]********************************************************************
Script file                             test6.bp
COM port                                /dev/ttyUSB2
- Opening serial port
[OK] Serial port open
- Resetting board
>>> ------------------------------------| # 
<<< #
<<< RE
<<< Bus Pirate v3.b clone w/different PIC
<<< Firmware v6.3-beta1 r2151  Bootloader v4.4
<<< DEVID:0x044F REVID:0x3003 (24FJ64GA004 A3)
<<< http://dangerousprototypes.com
<<< HiZ>
- Sending script file (test6.bp) - 13 lines
>>> ------------------------------------| s 
<<< s
<<< HiZ(BASIC)>
>>> ------------------------------------| new 
<<< new
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 10 AUX 1 
<<< 10 AUX 1
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 20 FOR I=1 TO 5 
<<< 20 FOR I=1 TO 5
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 30 LET A=ADC 
<<< 30 LET A=ADC
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 40 PRINT I;": ";A 
<<< 40 PRINT I;": ";A
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 50 DELAY 20 
<<< 50 DELAY 20
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 60 NEXT I 
<<< 60 NEXT I
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 70 AUX 0 
<<< 70 AUX 0
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 80 PRINT "WORK DONE" 
<<< 80 PRINT "WORK DONE"
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| list 
<<< list
<<< 
<<< 10  AUX 1
<<< 20  FOR I=1 TO 5
<<< 30  LET A= ADC 
<<< 40  PRINT I;": ";A
<<< 50  DELAY 20
<<< 60  NEXT I
<<< 70  AUX 0
<<< 80  PRINT "WORK DONE"
<<< 65535  END 
<<< 67 bytes.
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| run 
<<< run
<<< 1: 388
<<< 2: 387
<<< 3: 387
<<< 4: 387
<<< 5: 424
<<< WORK DONE
<<< 
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| exit 
<<< exit
<<< Ready
<<< HiZ>
- Closing serial port
```

Other scripts, those run longer, are not able to finish because TIMOUT is triggered and Python session is closed. I have to run these scripts from terminal (like minicom or picocom). An example, the same script as before but it runs longer (DELAY increased from 20 to 100):
```
$ cat test6a.bp 
s
new
10 AUX 1
20 FOR I=1 TO 5
30 LET A=ADC
40 PRINT I;": ";A
50 DELAY 100
60 NEXT I
70 AUX 0
80 PRINT "WORK DONE"
list
run
exit
```
```
$ python3 buspirate.py -c /dev/ttyUSB2 test6a.bp

***[ Bus Pirate scripting tool ]********************************************************************
Script file                             test6a.bp
COM port                                /dev/ttyUSB2
- Opening serial port
[OK] Serial port open
- Resetting board
>>> ------------------------------------| # 
<<< #
<<< Ready
<<< HiZ>
- Sending script file (test6a.bp) - 13 lines
>>> ------------------------------------| s 
<<< s
<<< HiZ(BASIC)>
>>> ------------------------------------| new 
<<< new
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 10 AUX 1 
<<< 10 AUX 1
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 20 FOR I=1 TO 5 
<<< 20 FOR I=1 TO 5
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 30 LET A=ADC 
<<< 30 LET A=ADC
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 40 PRINT I;": ";A 
<<< 40 PRINT I;": ";A
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 50 DELAY 100 
<<< 50 DELAY 100
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 60 NEXT I 
<<< 60 NEXT I
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 70 AUX 0 
<<< 70 AUX 0
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| 80 PRINT "WORK DONE" 
<<< 80 PRINT "WORK DONE"
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| list 
<<< list
<<< 
<<< 10  AUX 1
<<< 20  FOR I=1 TO 5
<<< 30  LET A= ADC 
<<< 40  PRINT I;": ";A
<<< 50  DELAY 100
<<< 60  NEXT I
<<< 70  AUX 0
<<< 80  PRINT "WORK DONE"
<<< 65535  END 
<<< 68 bytes.
<<< Ready
<<< HiZ(BASIC)>
>>> ------------------------------------| run 
<<< run
<<< 1: 388
>>> ------------------------------------| exit 
<<< 2: 387
- Closing serial port
```

So I think it could be helpful to have a way to tell Python program to wait longer before TIMOUT disconnects it from the BP. I am not sure what is the best way to do it. The BASIC program can run on BP device for hours...

**Comment by clvLabs** [comment]
The problem was using timeouts to assume the response from the BP had finished...

The text protocol used by the BP is not really meant to be parsed by a script (binary mode is there for a reason). Some responses include multiple lines (see the long message after `reset`) and I needed a way to decide when to stop waiting for more response lines. Took the wrong way :( and decided to use timeouts.

Since 2044233d5bbfc2252c30b179c7522eff997e5c68 the board response is checked to see if the last line received ends with a `>` (e.g. `HiZ>`). If so, the program stops waiting for more response lines.

What I've done with d0c6ed25f0aa3b8bd88b2da46342c8c5e355444b is completely removing the old timeout system and *only* wait for this kind of `EOT` substitute (the `>` character at the end of a received line).

**Beware** this may become a problem in a few situations:
* If you do something like `10 PRINT "TEST>"` in a `BASIC` script.
* If there's a real timeout communicating with the BP

Note the following variables have been removed from `config.py` (no longer needed):
* `SERIAL_RESPONSE_TIMEOUT`
* `SERIAL_RESPONSE_END_SILENCE`

I made a few changes to your `BASIC` example:
* Added comments (available from #4)
* Changed output text format
* Changed delay to 10s between measurements

```
s				// Enter BASIC mode
new				// Start new script
10 AUX 1
20 FOR I=1 TO 5
30 LET A=ADC
40 PRINT "Read #";I;" - Voltage: ";A
50 DELAY 10000
60 NEXT I
70 AUX 0
80 PRINT "WORK DONE"
run				// Run script
exit			// Exit BASIC mode
```

And run it with `--logmode`:

```
$ ./buspirate.py --logmode local/basic.txt
```

```
2020/10/09 01:41:56.243 >>>
2020/10/09 01:41:56.359 <<< HiZ>
2020/10/09 01:41:56.359 >>> #
2020/10/09 01:41:56.388 <<< #
2020/10/09 01:41:56.388 <<< RESET
2020/10/09 01:41:56.389 <<<
2020/10/09 01:41:56.389 <<< Bus Pirate v3b
2020/10/09 01:41:56.389 <<< Firmware v5.10 (r559)  Bootloader v4.4
2020/10/09 01:41:56.390 <<< DEVID:0x0447 REVID:0x3046 (24FJ64GA002 B8)
2020/10/09 01:41:56.390 <<< http://dangerousprototypes.com
2020/10/09 01:41:56.490 <<< HiZ>
2020/10/09 01:41:56.991 >>> s
2020/10/09 01:41:56.995 <<< s
2020/10/09 01:41:57.095 <<< HiZ(BASIC)>
2020/10/09 01:41:57.095 >>> new
2020/10/09 01:41:57.106 <<< new
2020/10/09 01:41:57.107 <<< Ready
2020/10/09 01:41:57.207 <<< HiZ(BASIC)>
2020/10/09 01:41:57.207 >>> 10 AUX 1
2020/10/09 01:41:57.218 <<< 10 AUX 1
2020/10/09 01:41:57.219 <<< 0x9D0x000x00Ready
2020/10/09 01:41:57.319 <<< HiZ(BASIC)>
2020/10/09 01:41:57.319 >>> 20 FOR I=1 TO 5
2020/10/09 01:41:57.340 <<< 20 FOR I=1 TO 5
2020/10/09 01:41:57.341 <<< 0x8A0x000x000x000x8B0x000x00Ready
2020/10/09 01:41:57.441 <<< HiZ(BASIC)>
2020/10/09 01:41:57.441 >>> 30 LET A=ADC
2020/10/09 01:41:57.452 <<< 30 LET A=ADC
2020/10/09 01:41:57.452 <<< 0x800x000x000x980x00Ready
2020/10/09 01:41:57.552 <<< HiZ(BASIC)>
2020/10/09 01:41:57.553 >>> 40 PRINT "Read #";I;" - Voltage: ";A
2020/10/09 01:41:57.580 <<< 40 PRINT "Read #";I;" - Voltage: ";A
2020/10/09 01:41:57.581 <<< 0x880x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x000x00Ready
2020/10/09 01:41:57.682 <<< HiZ(BASIC)>
2020/10/09 01:41:57.682 >>> 50 DELAY 10000
2020/10/09 01:41:57.703 <<< 50 DELAY 10000
2020/10/09 01:41:57.704 <<< 0x9C0x000x000x000x000x000x00Ready
2020/10/09 01:41:57.804 <<< HiZ(BASIC)>
2020/10/09 01:41:57.804 >>> 60 NEXT I
2020/10/09 01:41:57.815 <<< 60 NEXT I
2020/10/09 01:41:57.815 <<< 0x8C0x000x00Ready
2020/10/09 01:41:57.916 <<< HiZ(BASIC)>
2020/10/09 01:41:57.916 >>> 70 AUX 0
2020/10/09 01:41:57.926 <<< 70 AUX 0
2020/10/09 01:41:57.927 <<< 0x9D0x000x00Ready
2020/10/09 01:41:58.027 <<< HiZ(BASIC)>
2020/10/09 01:41:58.027 >>> 80 PRINT "WORK DONE"
2020/10/09 01:41:58.048 <<< 80 PRINT "WORK DONE"
2020/10/09 01:41:58.049 <<< 0x880x000x000x000x000x000x000x000x000x000x000x000x00Ready
2020/10/09 01:41:58.149 <<< HiZ(BASIC)>
2020/10/09 01:41:58.150 >>> run
2020/10/09 01:41:58.160 <<< run
2020/10/09 01:41:58.160 <<< READ #1 - VOLTAGE: 0
2020/10/09 01:42:11.327 <<< READ #2 - VOLTAGE: 0
2020/10/09 01:42:24.495 <<< READ #3 - VOLTAGE: 0
2020/10/09 01:42:37.662 <<< READ #4 - VOLTAGE: 0
2020/10/09 01:42:50.830 <<< READ #5 - VOLTAGE: 0
2020/10/09 01:43:03.997 <<< WORK DONE
2020/10/09 01:43:03.997 <<<
2020/10/09 01:43:03.997 <<< Ready
2020/10/09 01:43:04.098 <<< HiZ(BASIC)>
2020/10/09 01:43:04.098 >>> exit
2020/10/09 01:43:04.109 <<< exit
2020/10/09 01:43:04.109 <<< Ready
2020/10/09 01:43:04.209 <<< HiZ>
```

Oooooops!! It seems there is something more than 10s between reads...

```
01:41:58.160 <<< READ #1 - VOLTAGE: 0
01:42:11.327 <<< READ #2 - VOLTAGE: 0
01:42:24.495 <<< READ #3 - VOLTAGE: 0
01:42:37.662 <<< READ #4 - VOLTAGE: 0
01:42:50.830 <<< READ #5 - VOLTAGE: 0
``` 

... but that's another story

**Comment by clvLabs** [comment]
BTW @PSLLSP , I didn't know about `BASIC` mode and I find it's a VERY powerful mode when combined with this humble script. 
Would you mind if I use your `BASIC` example code in this project's `README`?

**Comment by clvLabs** [comment]
@PSLLSP , after making all these changes (logging, `BASIC`, etc) and testing them under Linux (I used to *live under* Windows when I first coded this script) I am seeing a **whole** new world of possibilities for the script!!!

If you are familiar with Linux imagine combining a `BP BASIC` voltage reading script with:
* `cron`/`watch`
* `tee`
* `grep`

As a simple example, I've created a `scripts/d.txt` containing a single `d` (single voltage read).

If I run `watch -n 1 "./buspirate.py local/d.txt -l | grep -i probe"`, I get a *free* continuous read every second.

```
Every 1,0s: ./buspirate.py local/d.txt -l | grep ...  taller: Fri Oct  9 03:20:31 2020

2020/10/09 03:20:31.889 <<< VOLTAGE PROBE: 0.00V
```

Combine `BP BASIC` with `Python` and standard Linux tools and you can make the craziest scheduling and triggering you can imagine.


If you want to make long-term measurements, i would recommend you to use a [Raspberry Pi](http://raspberrypi.org/) instead of your regular PC:
* You can connect your Raspberry to your network (Ethernet/Wifi) and have your *meter* away from your computer (more flexible).
* You are leaving a 12V device turned on instead of your PC (cheaper/safer).
* If you do a little Python scripting, you could even trigger measurements (or any other action the BP can do) from GPIO events on the Raspberry. It even has I2C!

**Comment by PSLLSP** [comment]
You can use my BASIC examples in README, I have no problem with that. There are more examples at github for BP. BASIC for BP is powerful extension to BP but there are many bugs in BP firmware :-(
I started my experiments with BP because I had about 100 color LEDs those blink "randomly" and I wanted to pick several of them those blink with similar pattern. The original idea was to use BP to measure voltage on LED, send values to PC and do some post-processing of data on PC to find frequency of blinking. At the end I wrote a BASIC script for BP, it measures the frequency of blinking and I was able to pick LEDs with similar blinking pattern.
BTW, those 2-pin color LEDs from ebay are great for experiments with BP, those could be used as an easy source of voltage that changes in time and several experiments can be setup to measure different characteristics.
